name: Check NPM with new lock file

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  check-npm-new-lock:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Print NPM version
      run: npm --version
    - name: Print NodeJS version
      run: node --version
    - run: rm -f package-lock.json
    - run: npm install
    - run: rm -rf node_modules
    - run: npm install
    - run: npm ci
